# Site settings
title: On Science and Tech
email: di.jiang*outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This site is under construction.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deene.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
